module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert('Users', [
      {
        firstName: 'Alice',
        lastName: 'Wonder',
        displayName: 'AliceW',
        password: 'hashedpassword1',
        email: 'alice.wonder@example.com',
        avatar: 'anon.png',
        role: 'creator',
        balance: 50,
        accessToken: null,
        rating: 4.8,
      },
      {
        firstName: 'Bob',
        lastName: 'Builder',
        displayName: 'BobB',
        password: 'hashedpassword2',
        email: 'bob.builder@example.com',
        avatar: 'anon.png',
        role: 'creator',
        balance: 10,
        accessToken: null,
        rating: 4.5,
      },
      {
        firstName: 'Charlie',
        lastName: 'Chaplin',
        displayName: 'CharlieC',
        password: 'hashedpassword3',
        email: 'charlie.chaplin@example.com',
        avatar: 'anon.png',
        role: 'creator',
        balance: 20,
        accessToken: null,
        rating: 4.9,
      },
      {
        firstName: 'Diana',
        lastName: 'Prince',
        displayName: 'DianaP',
        password: 'hashedpassword4',
        email: 'diana.prince@example.com',
        avatar: 'anon.png',
        role: 'creator',
        balance: 15,
        accessToken: null,
        rating: 4.7,
      },
      {
        firstName: 'Eve',
        lastName: 'Smith',
        displayName: 'EveS',
        password: 'hashedpassword5',
        email: 'eve.smith@example.com',
        avatar: 'anon.png',
        role: 'customer',
        balance: 100,
        accessToken: null,
        rating: 0,
      },
      {
        firstName: 'John',
        lastName: 'Doe',
        displayName: 'johnny',
        password: 'hashed_password',
        email: 'john.doe@example.com',
        avatar: 'anon.png',
        role: 'customer',
        balance: 0,
        rating: 0,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete('Users', null, {});
  },
};
